const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const root = process.env.WEAR_CLIENT_ROOT || path.resolve(__dirname, '..');
  let yandexMode = false;
  const server = http.createServer((req, res) => {
    res.setHeader('Content-Type', req.url.endsWith('.js') ? 'text/javascript' : 'text/html');
    if (req.url === '/js/wear-config.js') return res.end(`export const WEAR_AUTH_ENDPOINT='${yandexMode ? 'https://functions.yandexcloud.net/test-function' : 'https://pairing.test'}';`);
    if (req.url === '/js/wear-pairing.js') return res.end(fs.readFileSync(path.join(root, 'js/wear-pairing.js')));
    res.end(`<div id="profileDocuments"></div><script>window.uid='owner';window.getFirebaseIdToken=async()=>window.uid?'test-token':null;window.nutritionStore={getAccountProfileDefaults:()=>({uid:window.uid})};</script><script type="module" src="/js/wear-pairing.js"></script>`);
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || undefined });
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const calls = [];
    await page.route('https://pairing.test/**', async route => {
      calls.push(new URL(route.request().url()).pathname);
      assert.equal(route.request().headers().authorization, 'Bearer test-token');
      await route.fulfill({ status: 200, contentType: 'application/json', body: '{"status":"pending"}' });
    });
    await page.goto(`http://127.0.0.1:${server.address().port}/#connect-watch=01234567`);
    await page.locator('#wearPairingDialog').waitFor();
    assert.equal(calls.length, 0, 'hash must not automatically approve');
    assert.equal(await page.locator('input[name=code]').inputValue(), '0123-4567');
    assert.equal(await page.locator('input[name=code]').getAttribute('inputmode'), 'numeric');
    await page.getByRole('button', { name: 'Проверить код' }).click();
    await page.getByRole('button', { name: 'Подтвердить подключение' }).waitFor();
    assert.deepEqual(calls, ['/inspect']);
    await page.evaluate(() => { window.uid = 'another'; });
    await page.getByRole('button', { name: 'Подтвердить подключение' }).click();
    await page.getByText('Аккаунт изменился. Проверьте код заново.').waitFor();
    assert.deepEqual(calls, ['/inspect'], 'account change must require a fresh confirmation');
    await page.getByRole('button', { name: 'Проверить код' }).click();
    await page.getByRole('button', { name: 'Подтвердить подключение' }).waitFor();
    await page.getByRole('button', { name: 'Подтвердить подключение' }).click();
    await page.getByText('Подтверждено. Дождитесь завершения входа на часах.').waitFor();
    assert.deepEqual(calls, ['/inspect', '/inspect', '/approve']);
    await page.getByRole('button', { name: 'Закрыть' }).click();
    await page.getByRole('button', { name: 'Подключить часы', exact: true }).click();
    const codeInput = page.locator('input[name=code]');
    await codeInput.pressSequentially('01234567');
    assert.equal(await codeInput.inputValue(), '0123-4567');
    await codeInput.fill('1234-5678');
    assert.equal(await codeInput.inputValue(), '1234-5678');
    await codeInput.fill('00000000');
    assert.equal(await codeInput.inputValue(), '0000-0000');
    await page.locator('input[name=code]').fill('123');
    await page.getByRole('button', { name: 'Проверить код' }).click();
    await page.getByText('Введите 8 цифр кода с ваших часов.').waitFor();
    await page.evaluate(() => { window.uid = ''; });
    await page.locator('input[name=code]').fill('01234567');
    await page.getByRole('button', { name: 'Проверить код' }).click();
    await page.getByText('Сначала войдите в аккаунт в профиле приложения.').waitFor();
    assert.equal(calls.length, 3);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#wearPairingDialog').count(), 0);
    yandexMode = true;
    const yandexPage = await browser.newPage();
    const yandexCalls = [];
    await yandexPage.route('https://functions.yandexcloud.net/**', async route => {
      const request = route.request();
      const url = new URL(request.url());
      assert.equal(url.pathname, '/test-function');
      assert.equal(request.headers()['x-x20-authorization'], 'Bearer test-token');
      assert.equal(request.headers().authorization, undefined);
      yandexCalls.push(url.searchParams.get('action'));
      await route.fulfill({ status: 200, contentType: 'application/json', body: '{"status":"pending"}' });
    });
    await yandexPage.goto(`http://127.0.0.1:${server.address().port}/#connect-watch=01234567`);
    await yandexPage.getByRole('button', { name: 'Проверить код' }).click();
    await yandexPage.getByRole('button', { name: 'Подтвердить подключение' }).waitFor();
    await yandexPage.getByRole('button', { name: 'Подтвердить подключение' }).click();
    await yandexPage.getByText('Подтверждено. Дождитесь завершения входа на часах.').waitFor();
    assert.deepEqual(yandexCalls, ['inspect', 'approve']);
    console.log('PASS: Yandex query actions and application auth header');
    console.log('PASS: explicit two-step approval, account change, invalid code, guest, cancellation');
  } finally { await browser?.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
